### PR TITLE
Feat/finishing touches v0.0.1

### PR DESCRIPTION
**Pull request by domhoward14**

### CODE REVIEW

**Comment by anilsenay** [comment]
@domhoward14 hey, sorry for missing this pull request. I checked your repository and you made a lot of changes which I am grateful. If you decide to open a pull request again, I will review it and possibly merge it. I am so sorry for that I can't spare time for swagno and neglected it. If you are really interested in swagno, I can also give you write permission for this repository and you can lead this project. Thank you for all your good efford.

**Comment by domhoward14** [comment]
Thank you for reaching out, @anilsenay! I apologize but I mistakenly tried to merge my PR into the master branch of your repo last night. I am still getting the hang of using Github. A few weeks ago, I opened a smaller PR, but I assumed you weren't receiving the notifications for this project. As a result, I continued working on it in my forked repo. As you may have saw I made breaking changes. If you are comfortable with me pushing these changes, and creating a version to begin tracking then I can open another pull request. However, if you prefer, I can also keep it as is in my forked repo. Which ever you prefer works for me :). Once again, I really love your swagno idea, and thank you for reaching out!

**Comment by anilsenay** [comment]
@domhoward14 Ah yes unfortunately, I missed notifications or I left them to review later and forgot. There are some opened PRs like that. I created swagno earlier in my Golang adventure so I know its API is sooo ugly and not user friendly. And later I was lazy to refactor 😓. So when I looked at your PR, it was possibly how I would design its API if I created swagno nowadays 😄 Your breaking changes are fine to me, we can publish it as v1.0.0 then. I would be glad to merge them. 

Of course, you can keep your forked repo and we can sync them when you change something in your repo by opening PR to here. That would even be better approach instead of directly doing development in this repository.

Please open pull request from your repository to swagno then we can merge it and release a version as v1.0.0
I will also invite you to swagno organisation and you will be write access for swagno. So you can merge your changes and review other pull requests. Also I will try to be more contributor after this.

Thank you for all your interest 🥳

**Comment by domhoward14** [comment]
@anilsenay lol yeah, I completely understand what you mean. It's really impressive that you were able to accomplish such a task early on in your learning journey. It's much better than the simple hello world projects I was doing when I first started learning 😅.

I'm also happy to hear that you'll be able to contribute more to the project in the future! I truly see its value. Swaggo is a significant project, and the differences between this one and that are mainly based on user preferences. Personally, I find this approach much better than using annotations, and the ability to add validation through code enhances the workflow for developers who may not be well-versed in OAS. So, after all that rambling, I just wanted to say that I think this is an excellent project, and I'm excited to see how far we can take it 😁!

oh also, heads up. I may have forgotten to put back some of the stuff from the README when i was refactoring. So if you wonder why any stuff like that is missing  when reviewing it may just be because it got temporarily removed during refactoring.

**Pull request closed without merging**
